### ISSUE TITLE
change http.createServer to http.listen.

### ISSUE THREAD

**Issue by cdhit** [Money-Manager-SaaS/mmss-backend#10]
First change in **other changes** in [Express 4](http://expressjs.com/en/guide/migrating-4.html#other-changes) : `http.createServer()`. 
Description: The http module is no longer needed, unless you need to directly work with it (socket.io/SPDY/HTTPS). The app can be started by using the app.listen() function.

This version is express 5.0.0-alpha.7. 

Consider to use `http.listen()` instead in `server.ts`?

**Comment by tim-hub** [comment]
https://github.com/Money-Manager-SaaS/mmss-backend/commit/2b6954a739835c3cb563b541481574fe797cacb3
