### ISSUE TITLE
@tim-hub

### ISSUE THREAD

**Issue by girl817** [Money-Manager-SaaS/mmss-backend#30]
Created a new branch:create_entity_for_all_service for API end to end test, it has a problem when test update function. 
need to check and fix update function, thanks.

**Comment by tim-hub** [comment]
sorry I cannot reproduce this error.

update works fine on my side.

![image](https://user-images.githubusercontent.com/2884320/82417230-c3c68680-9a6a-11ea-981e-dbda40509a70.png)

if the error still happens, paste the error message and the logs please

**Comment by tim-hub** [comment]
I assume you did something wrong in your put request
