### ISSUE TITLE
foreign keys and indexes missing

### ISSUE THREAD

**Issue by cdhit** [Money-Manager-SaaS/mmss-backend#43]
![image](https://user-images.githubusercontent.com/1721125/83714903-36954b80-a680-11ea-9be8-b3eded9efb6f.png)
![image](https://user-images.githubusercontent.com/1721125/83714909-3d23c300-a680-11ea-8a62-9d9e7a8ad4a6.png)

From the transactions API: error: 
SequelizeDatabaseError: SQLITE_ERROR: no such column: ledgerID at Query.formatError (C:\Users\DonChan\PycharmProjects\mmss-backend\node_modules\sequelize\lib\dialects\sqlite\query.js:422:16) at Query._handleQueryResponse (C:\Users\DonChan\PycharmProjects\mmss-backend\node_modules\sequelize\lib\dialects\sqlite\query.js:73:18) at afterExecute (C:\Users\DonChan\PycharmProjects\mmss-backend\node_modules\sequelize\lib\dialects\sqlite\query.js:250:31) at Statement.errBack (C:\Users\DonChan\PycharmProjects\mmss-backend\node_modules\sqlite3\lib\sqlite3.js:16:21)

From the sqlite DB. only a primary key. Non index and foreign keys.

**Comment by tim-hub** [comment]
try delete demo.db or something

this is more like issue on local dev environment.

cannot really reproduce.
